name = "StateBins"
uuid = "9a95ff34-6502-4c8e-98bc-9434865e63ed"
authors = ["technocrat <public@careaga.net>"]
version = "0.1.1"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"

[targets]
test = ["Test", "Aqua"]

[compat]
julia = "1.6"
Colors = "1.13"
ColorSchemes = "3.24"
DataFrames = "1.6"
Aqua = "0.8"
Documenter = "1"
Test = "1"
